#!/bin/sh
cd daemontools-$PACKAGEVERSION
sed -i -e 's#gcc#gcc -include /usr/include/errno.h #g' src/conf-cc
sh package/compile
mkdir -p $DESTDIR$PREFIX/bin
install -m755 command/* $DESTDIR$PREFIX/bin

