#!/bin/sh

./configure --prefix=/usr  \
  --with-terminfo=/usr/share/terminfo \
  --enable-wide-glyphs \
  --enable-unicode3 \
  --enable-iso14755 \
  --enable-frills \
	--enable-256-color \
	--with-term=rxvt-256color || return 1
make -j8 || return 1
make install DESTDIR=$DESTDIR
