#!/bin/sh
./configure --prefix=$PREFIX --enable-shared --with-threads --enable-ipv6 \
                             --enable-unicode=ucs4 --with-system=expat \
                             --with-system-ffi --with-dbmliborder=gdbm:ndbm
make
make install DESTDIR=$DESTDIR
