#!/bin/bash


root=$(dirname $PYTHON)
$root/pip install --root $DESTDIR -r requirements.txt || exit 1
$root/python ./setup.py build || exit 1
$root/python ./setup.py install --root $DESTDIR  || exit 1
